name: ghost_rigger
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flame: ^0.22.1
  animated_text_kit: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "#000000"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/bgm/menu.mp3
    - assets/audio/bgm/music.mp3
    - assets/audio/bgm/ingame.mp3
    - assets/audio/bgm/intro.mp3
    - assets/audio/sfx/block.wav
    - assets/audio/sfx/menu.aac

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Italic.ttf
          style: italic
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700

    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Light.ttf
          weight: 300
        - asset: assets/fonts/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rajdhani-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rajdhani-Bold.ttf
          weight: 700
